version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-local
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "3035:3035"
    # Required for debug breakpoints
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
